### ISSUE TITLE
Installation & update site doesn't work anymore

### ISSUE THREAD

**Issue by gerrit-hohl** [Jamling/eclipse-explorer#3]
I got an error during a search for updates in Eclipse that the site [https://www.ieclipse.cn/PDESite/updates/](https://www.ieclipse.cn/PDESite/updates/) doesn't work anymore. When opening the page in a browser it also look a little bit strange.

Eclipse IDE for Java Developers
Version: 2024-06 (4.32.0)
Build id: 20240606-1231

Please let me know if you need more information.

**Comment by Jamling** [comment]
Please use new update site https://dl.ieclipse.cn/updates/

**Comment by gerrit-hohl** [comment]
Changed it, works. Thanks a lot. 🙏
